// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/usecases/segment.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mahsandr/arman-challenge/internal/domain/models"
)

// MockSegmentService is a mock of SegmentService interface.
type MockSegmentService struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentServiceMockRecorder
}

// MockSegmentServiceMockRecorder is the mock recorder for MockSegmentService.
type MockSegmentServiceMockRecorder struct {
	mock *MockSegmentService
}

// NewMockSegmentService creates a new mock instance.
func NewMockSegmentService(ctrl *gomock.Controller) *MockSegmentService {
	mock := &MockSegmentService{ctrl: ctrl}
	mock.recorder = &MockSegmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentService) EXPECT() *MockSegmentServiceMockRecorder {
	return m.recorder
}

// AddUserSegment mocks base method.
func (m *MockSegmentService) AddUserSegment(ctx context.Context, segment *models.UserSegment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserSegment", ctx, segment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserSegment indicates an expected call of AddUserSegment.
func (mr *MockSegmentServiceMockRecorder) AddUserSegment(ctx, segment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserSegment", reflect.TypeOf((*MockSegmentService)(nil).AddUserSegment), ctx, segment)
}
